### ISSUE TITLE
allow (require)ing modules written in alive

### ISSUE THREAD

**Issue by s-ol** [s-ol/alivecoding#16]
I see two ways of making this work:

1. the root scope of the included file is imported
   - pro:
     - simple
     - doesn't need any other language features
   - con:
     - imports will be re-exported, e.g.
       ```
       (import* math)
       (defn plus-two-times-three (a) (* (+ 2) 3)))
       ```
       will export all of `math` and cause problems when importing.
     - this is a real problem so there will have to be some hacky workaround, like having 'public' and 'private' declarations, so that `import*` and `import` create private declarations, while `def` and `defn` create public declarations.
2. import the value of the last expression in a file, add a way to define scopes
   - pro:
     - solves the issue above
   - con:
     - requires thinking very hard about composite types

**Comment by s-ol** [comment]
@noizhardware could you elaborate on how you would have expected this to work?

**Comment by noizhardware** [comment]
the way I'd expect it to work:
* importing (or "loading", might be more appropriate) is added to the preexisting order, so the "import" basically works as copy-pasting that specific file in place of the (load file)
* for the problem of the imports being re-exported, maybe you could check always if an import on that item has already been run. Basically be sure that if something gets imported once, all successive import attempts will be ignored. Not sure how to solve the fact things can be (import* or (import, but I'm sure there's a way to solve that.

**Comment by s-ol** [comment]
So there is now three ways to make alive modules, using two new builtins, [`export`][exp] and [`export*`][exps]:

`main.alv`
```
(import* my-module)

(print exported)
```

`my-module.alv`
```
(def exported "hello world")

#(export everything in the file. this will cause
  problems when a lot of other stuff is imported!)
(export*)
```

```
(def exported "hello world")

#(export only specified symbols)
(export* exported)
```

```
#(create a new scope and export everything
  that was defined inside it)
(export
  (def exported "hello world"))
```

In all cases the `(export)` has to be the last expression in the `alv` file,
since when you `(require)` (or import) an alive file, you get the value of the last expression in that file.

[exp]: https://alive.s-ol.nu/master/reference/index.html#export
[exps]: https://alive.s-ol.nu/master/reference/index.html#export*

**Comment by s-ol** [comment]
There is still some bugs with this:

- [x] the handling of `children` results wrt. runtime dependencies has to be checked, i think it is leaking references
- [x] the implicit `(do)` in the root of the embedded file is causing a tag-collision warning on every import.
- [x] the imported file isnt tagged, which means that state will be unecessarily lost on reloads unless the file is already tagged. Imported files should be tagged just like the main file, and a warning should be thrown if they are read-only.
- [x] make imports relative to importing-file
- [x] cache imported modules to avoid doubly-executing code

**Comment by s-ol** [comment]
I think this is done :slightly_smiling_face: The `:destroy()` ing of Ops is still a bit of a touchy subject, and needs thorough testing. but it never worked properly, so its shouldnt hold this back from going onto master ;)
